ci: prepare again master for feature/foundry merge

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -304,47 +304,25 @@ jobs:
       # A tiny bit hacky, but it's simple and works
       run: echo "mangrove_built=true" >> $GITHUB_ENV
 
-    # Run Solidity tests and report
-    - name: Mangrove Solidity Tests
-      run: yarn run test:solidity
+    # Run local Solidity tests
+    - name: Mangrove Local Solidity Tests
+      run: yarn run test:solidity:local
 
-    - name: Mangrove Solidity Test Report
-      uses: dorny/test-reporter@v1
-      if: ${{ env.mangrove_built && (success() || failure()) }}
-      with:
-        name: Solidity Tests                  # Name of the check run which will be created
-        path: ${{env.working-directory}}/solidity-mocha-test-report.json # Path to test results
-        reporter: mocha-json                  # Format of test results
-
-    # NOTE: Etherium mainnet tests disabled for now, while we focus on Polygon
-    # 
-    # # == Run test suite Ethereum mainnet ==
-    # - name: Mangrove Ethereum mainnet Tests
-    #   run: yarn run test:ethereum-mainnet
-    #   env:
-    #     ETHEREUM_NODE_URL: ${{ secrets.ETHEREUM_NODE_URL }}
-
-    # - name: Mangrove Ethereum mainnet Test Report
-    #   uses: dorny/test-reporter@v1
-    #   if: ${{ env.mangrove_built && (success() || failure()) }}
-    #   with:
-    #     name: Ethereum mainnet Tests          # Name of the check run which will be created
-    #     path: ${{env.working-directory}}/ethereum-mainnet-mocha-test-report.json # Path to test results
-    #     reporter: mocha-json                  # Format of test results
-
-    # == Run test suite Polygon mainnet == 
-    - name: Mangrove Polygon mainnet Tests
-      run: yarn run test:polygon-mainnet
+    # Run polygon Solidity tests
+    - name: Mangrove Polygon Solidity Tests
+      run: yarn run test:solidity:polygon
       env:
         POLYGON_NODE_URL: ${{ secrets.POLYGON_NODE_URL }}
 
-    - name: Mangrove Polygon mainnet Test Report
-      uses: dorny/test-reporter@v1
-      if: ${{ env.mangrove_built && (success() || failure()) }}
-      with:
-        name: Polygon mainnet Tests           # Name of the check run which will be created
-        path: ${{env.working-directory}}/polygon-mainnet-mocha-test-report.json # Path to test results
-        reporter: mocha-json                  # Format of test results
+    # NOTE: uncomment once you can manage forge test 
+    # outputs in gh actions
+    # - name: Mangrove Solidity Test Report
+    #   uses: dorny/test-reporter@v1
+    #   if: ${{ env.mangrove_built && (success() || failure()) }}
+    #   with:
+    #     name: Solidity Tests                  # Name of the check run which will be created
+    #     path: ${{env.working-directory}}/solidity-mocha-test-report.json # Path to test results
+    #     reporter: mocha-json                  # Format of test results
 
     # save artifacts for later stages
     - name: Zip output
@@ -613,6 +591,8 @@ jobs:
     # == build == 
     - name: Mangrove.js build
       run: yarn run build-this-package
+      env:
+        NODE_OPTIONS: "--max_old_space_size=8192"
 
     - name: Save status of build
       run: echo "mangrove_js_built=true" >> $GITHUB_ENV      
