added job for failing offer bot

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1139,6 +1139,125 @@ jobs:
         SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
   # ==== End job: bot-taker-greedy ====        
 
+ # ==== Job: Build and test bot-offer-failing ====
+  bot-failing-offer:
+    needs: [security-guard, commonlib-js, mangrove-solidity, mangrove-js, bot-utils]
+
+    runs-on: ubuntu-latest
+
+    env:
+      working-directory: packages/bot-failing-offer
+
+    defaults:
+      run:
+        working-directory: ${{env.working-directory}}
+
+    strategy:
+      matrix:
+        node-version: [16.x]
+
+    steps:
+
+    # == Git checkout ==
+    - name: Checkout
+      uses: actions/checkout@v3
+      # Workaround for https://github.com/npm/cli/issues/2610
+      with:
+        persist-credentials: false
+        ref: ${{ env.GIT_REF_TO_TEST }}
+        submodules: recursive
+
+    - name: Reconfigure git to use HTTP authentication
+      # Workaround for https://github.com/npm/cli/issues/2610    
+      run: >
+        git config --global url."https://github.com/".insteadOf
+        ssh://git@github.com/
+
+    # == yarn setup ==
+    - name: Yarn setup (caching yarn dependencies)
+      uses: actions/setup-node@v3
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'yarn'
+
+    - run: yarn install --immutable
+      working-directory: . # Yarn must run in root to ensure monorepo setup
+
+    - name: Foundry Setup
+      uses: ./.github/actions/foundry-setup
+      
+    # == download and unzip artefacts ==
+    - name: Download cached mangrove-solidity artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: mangrove-solidity-out.zip
+
+    - name: Unzip mangrove-solidity artifact
+      uses: montudor/action-zip@v1
+      with:
+        args: unzip -qq mangrove-solidity-out.zip
+
+    - name: Download cached mangrove-js artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: mangrove-js-out.zip
+
+    - name: Unzip mangrove-js artifact
+      uses: montudor/action-zip@v1
+      with:
+        args: unzip -qq mangrove-js-out.zip
+
+    - name: Download cached commonlib.js artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: commonlib-out.zip
+
+    - name: Unzip commonlib.js artifact
+      uses: montudor/action-zip@v1
+      with:
+        args: unzip -qq commonlib-out.zip
+    
+    - name: Download cached bot-utils artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: bot-utils-out.zip
+
+    - name: Unzip bot-utils artifact
+      uses: montudor/action-zip@v1
+      with:
+        args: unzip -qq bot-utils-out.zip
+
+    # == build ==
+
+    - name: Failing Offer Bot - Build
+      run: yarn run build-this-package
+
+    - name: Save status of build
+      run: echo "bot_failing_offer_built=true" >> $GITHUB_ENV    
+
+    # == run and report tests == 
+    - name: Failing Offer Bot - Tests
+      run: yarn run test:coverage
+
+    - name: Failing Offer Bot - Test Report
+      uses: dorny/test-reporter@v1
+      if: ${{ env.bot_failing_offer_built && (success() || failure()) }}
+      with:
+        name: Failing Offer Bot - Tests                                # Name of the check run which will be created
+        path: packages/bot-failing-offer/coverage-tests-report.json # Path to test results
+        reporter: mocha-json                                         # Format of test results
+        
+    - name: Report Failure to Slack
+      if: ${{ failure() && fromJSON(env.NOTIFY_SLACK_FOR_THIS_WORKFLOW_RUN) }}
+      uses: ravsamhq/notify-slack-action@v1
+      with:
+        status: ${{ job.status }}
+        message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}> at {job}'
+        footer: '<{run_url}|View Run>'
+      env:
+        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
+  # ==== End job: bot-failing-offer ====        
+
   # ==== Job: Build and test bot-template ====
   bot-template:
     needs: [security-guard, commonlib-js, mangrove-solidity, mangrove-js, bot-utils]
@@ -1261,8 +1380,10 @@ jobs:
     - mangrove-solidity-doc
     - mangrove-js
     - mangrove-js-doc
+    - bot-utils
     - bot-cleaning
     - bot-maker-noise
+    - bot-failing-offer
     - bot-taker-greedy
     - bot-template
     - bot-updategas
